name: continous-integration-Marcus_Declementi.yml

on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          BRANCH_NAME: ${{ github.ref }}
    steps:
    - name: verify branch
      uses: actions/checkout@master
    - name: Parse branch name
      id: parse_branch
      run: echo "::set-env name=BRANCH_NAME::${GITHUB_REF#refs/heads/}"
      
    - name: Use branch name
      run: |
        echo "Branch name is $BRANCH_NAME"
    - name: envsubst-action
      uses: nowactions/envsubst@v1
      with:
        input: ./credentials.ini.tpl
        output: ./credentials.ini
    - name: Pruebas de SAST
      run: echo "Ejecuci√≥n de pruebas de SAST"
    - name: Crear archivo de credenciales
      run: |
        export USERNAME=${USERNAME}
        export PASSWORD=${PASSWORD}
        envsubst < credentials.ini.tpl > /tmp/credentials.ini
    - name: Addear cambios al repo
      run: |
        git config --global user.email "marcusdeclementi@gmail.com"
        git config --global user.name "mdeclementi"
        git add credentials.ini
        git commit -m "Add credentials.ini"
    - name: Pushear cambios al repo
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ env.BRANCH_NAME }}
    - name: Build docker image
      run: |
        docker build -t devops_ws . --tag devops_ws_$(date +%s)
